### ISSUE TITLE
Allow specifying Markdown heading levels

### ISSUE THREAD

**Issue by BWPanda** [spring-io/github-changelog-generator#56]
Is it possible to specify the level of the headings in the Markdown file?

For example, currently my Markdown is being output like so:

```markdown
## Bug fixes

- ...
```

But I'd instead like it to be:

```markdown
### Bug fixes

- ...
```

Obviously I can make these changes manually after the Markdown file has been generated, but I was hoping to automate it...

**Comment by philwebb** [comment]
It's currently hard coded in [ChangelogGenerator](https://github.com/spring-io/github-changelog-generator/blob/b49f1cb03fb3cff4facf95ec343b50bb9f7ad561/src/main/java/io/spring/githubchangeloggenerator/ChangelogGenerator.java#L149). It shouldn't be too hard to change that code to accept a configuration option.

**Comment by MysterAitch** [comment]
I have just submitted a PR to allow for a configurable prefix that introduces `defaultTitlePrefix` (defaulting to `## ` for backwards compatability). 

Despite this, I cannot help but wonder if the idea of a prefix / heading level should be removed entirely, and just have it configured via the title itself - for example, to get level three headings:

```yml
changelog:
  repository: testorg/testrepo
  sections:
  - title: "### :star: New Features"
    labels: ["enhancement"]
    sort: "created"
  - title: "### Bugs"
    labels: ["bug"]
    group: "test"
  issues:
    sort: title
    exclude:
      labels: ["hide"]
  contributors:
    title: "### Nice one!"
    exclude:
      names: ["philwebb"]
  external_links:
  - name: "### Release Notes 1"
    location: "url1"
  - name: "Release Notes 2"
    location: "url2"
```
