### ISSUE TITLE
Additional configuration options

### ISSUE THREAD

**Issue by MysterAitch** [spring-io/github-changelog-generator#60]
I have been working on quite a few configuration options to tweak the output so that it matches our current changelog format.

The fork is available at: https://github.com/MysterAitch/github-changelog-generator
Here's a diff: https://github.com/spring-io/github-changelog-generator/compare/master...MysterAitch:master

Some notable bits: 
- Configurable bullet styles (we use `*` rather than `-`)
- Ability to exclude issues from the changelog (we include PRs and issues in the milestone, but only PRs in the changelog)
- Option to label whether the changelog entry is an issue or a pull request
- Option to include an "everything else" section (i.e., issues/prs within the milestone that aren't included elsewhere within the changelog)

Is there any appetite for any of this to be shared back? :+1:

**Comment by MysterAitch** [comment]
Rather than list it all though, here is the configuration I am currently using with this forked version and an exported jar. 

The defaults for each of these are configured with backwards-compatible defaults, and they should probably be tidied up / nested within an `outputFormat` or similar option. I only realised this after doing it though haha.

```yml
changelog:
  repository: "javaparser/javaparser"
  milestone-reference: "ID"
  bulletStyle: "* "
  defaultTitlePrefix: "### "
  wrapIssueLinkInBrackets: true
  includeIssueOrPrPrefix: true
  includePrAuthor: true
  excludePullRequests: false
  excludeIssues: true
  includeWildcardSection: true
  sections:
    - title: "Highlights"
      labels: [ "PR: Noteworthy", "PR: Security", "PR: Deprecated", "PR: Deprecation" ]
      group: "highlights"
    - title: "API or Behaviour Change"
      labels: [ "API or Behaviour Change" ]
      group: "api change"
    - title: "Added"
      labels: [ "PR: Added" ]
    - title: "Changed"
      labels: [ "PR: Changed" ]
    - title: "Deprecated"
      labels: [ "PR: Deprecated", "PR: Deprecation" ]
    - title: "Removed"
      labels: [ "PR: Removed" ]
    - title: "Fixed"
      labels: [ "PR: Fixed", "PR: Bugfix",  "PR: Fix", "fix", "bug", "regression" ]
    - title: "Security"
      labels: [ "PR: Security" ]
    - title: "Developer Changes"
      labels: [ "PR: Build", "PR: Development", "builds / releases", "dependencies" ]
    - title: "Uncategorised"
      labels: [ "*" ]
  contributors:
    thankYouMessage: "Thank You to all contributors who worked on this release!"
    exclude:
      names: [ "dependabot[bot]", "renovate[bot]" ]
```
