### ISSUE TITLE
Excluded contributors `*` not working

### ISSUE THREAD

**Issue by morluna** [spring-io/github-changelog-generator#75]
I have a `release-notes.yml` config file in my project with the following content:

```yml
changelog:
  contributors:
    exclude:
      names: ["*"]
```

I'm expecting for the generated changelog to not include the contributors section. However, I keep getting this:
```md
## :beetle: Bug Fixes
...

## :heart: Contributors

We'd like to thank all the contributors who worked on this release!

- [@iAmericanBoy](https://github.com/iAmericanBoy)
- [@morluna](https://github.com/morluna)

```

Am I doing something wrong or not understanding what it means to actually exclude contributors?

**Comment by morluna** [comment]
Actually doing extra digging, it seems that even the title property isn't working:

```yml
changelog:
  contributors:
    title: "Awesome Contributors"
```

Still outputs:
```md
...
## :heart: Contributors
...
```
